


## Mybatis 配置
mybatis:
  type-aliases-package: com.knight.ucenter.dao.model
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/knight
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 2127


